{% set name = "dagster-cloud" %}
{% set version = "1.7.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagster-cloud-{{ version }}.tar.gz
  sha256: cb00ae1bd327596aed5e4ea62e4bb54479ff7caf324b0bbc2c93275e96b7b4b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dagster =={{ version }}
    - dagster-cloud-cli =={{ version }}
    - questionary
    - requests
    - typer
    - pex

test:
  imports:
    - dagster_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/dagster-io/dagster-cloud
  summary: Cloud support for Dagster

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
